name:                registry2nix
version:             0.1.0.0
github:              "codedownio/registry2nix"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/registry2nix#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- exceptions
- filepath
- monad-logger
- optparse-applicative
- process
- sandwich
- string-interpolate
- text
- time
- tomland
- unordered-containers
- validation-selective

default-extensions:
- GHC2021
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- DerivingStrategies
- DerivingVia
- ViewPatterns
- LambdaCase

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

library:
  source-dirs: src

executables:
  registry2nix-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - registry2nix

tests:
  registry2nix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - registry2nix
