
resolver: "lts-20.26"

nix:
  pure: false
  packages:
  - zlib

packages:
- .

extra-deps:
- tomland-1.3.3.2
- validation-selective-0.1.0.2

- github: codedownio/sandwich
  commit: c8bd19da96b8ecafe99ab783be890f16af5aaff5
  subdirs:
  - sandwich
