name: general

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 12 * * *' # Every day at noon

jobs:
  regenerate-general:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:release-22.11
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix-prefetch-git
      run: |
        nix profile install nixpkgs#nix-prefetch-git

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: "9.2.7"
        stack-version: "latest"
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-9.2.7-stack-2

    - name: Build
      run: |
        stack build --system-ghc

    - name: Install
      run: |
        stack install --system-ghc

    - name: Check out latest JuliaRegistries/General repo
      uses: actions/checkout@v3
      with:
        repository: "JuliaRegistries/General"
        path: JuliaRegistriesGeneral

    - name: Check out latest CodeDownIO/General repo
      uses: actions/checkout@v3
      with:
        repository: "CodeDownIO/General"
        path: CodeDownIOGeneral

    - name: Generate the update
      run: |
        registry2nix-exe \
          --print-failures \
          --repo JuliaRegistriesGeneral \
          --initial-repo CodeDownIOGeneral \
          --ignore-previous-failures CodeDownIOGeneral/failures.yml \
          --write-new-failures JuliaRegistriesGeneral/failures.yml \
          --num-workers 15

    - name: Sync the changes
      run: |
        # Tricky method to ensure the commit we're about to create for CodeDownIOGeneral
        # exactly matches the new state of JuliaRegistries
        rm -rf JuliaRegistries/.git
        mv CodeDownIOGeneral/.git JuliaRegistries/
        cd JuliaRegistries/
        git status
