name: general

on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 12 * * *' # Every day at noon

jobs:
  regenerate-general:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: "9.2.7"
        stack-version: "latest"
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-9.2.7-stack

    # - name: apt
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y libx11-dev libxext-dev libxinerama-dev libxrandr-dev libxss-dev

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Check out latest JuliaRegistries/General repo
      uses: actions/checkout@v3
      with:
        repository: "JuliaRegistries/General"
        path: JuliaRegistriesGeneral

    - name: Check out latest CodeDownIO/General repo
      uses: actions/checkout@v3
      with:
        repository: "CodeDownIO/General"
        path: CodeDownIOGeneral

    - name: Check everything looks good
      run: |
        echo "---------------"
        ls -lh
        echo "---------------"
        ls -lh JuliaRegistriesGeneral
        echo "---------------"
        ls -lh CodeDownIOGeneral

    - name: Generate the update
      run: |
        stack run -- \
          --print-failures \
          --repo JuliaRegistriesGeneral \
          --initial-repo CodeDownIOGeneral \
          --ignore-previous-failures CodeDownIOGeneral/failures.yml \
          --write-new-failures JuliaRegistriesGeneral/failures.yml \
          --num-workers 15

    - name: See what changed in JuliaRegistriesGeneral/failures
      run: |
        cd JuliaRegistriesGeneral
        git status
        git diff
