name: general

on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron:  '0 12 * * *' # Every day at noon

jobs:
  regenerate-general:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:release-22.11
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install nix-prefetch-git
      run: |
        nix profile install nixpkgs#nix-prefetch-git

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: "9.2.7"
        stack-version: "latest"
        enable-stack: true

    - name: Cache ~/.stack
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-9.2.7-stack-2

    - name: Build
      run: |
        stack build --system-ghc
